### PR TITLE
Adjusted for post request

### LINKED ISSUE #14: Redirect back after setting the cookie
### What steps will reproduce the problem?
Using the widget as it is.

### What is the expected result?
The get param should be removed after setting the cookie

### What do you get instead? (A Screenshot can help us a lot!)
Some seo tools give warnings due to the acceptCookies param

Something like this solves the problem...
```
if ($acceptCookies == '1') {
      $this->setPrivacyCookieValue(true);
      Yii::$app->response->redirect(Yii::$app->request->referrer);
}
```

### PR DESCRIPTION
**Pull request by JohnnyMcWeed**
### What are you changing/introducing
Use post instead of get

### QA
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | closes #14

### CODE REVIEW

**Comment by nadar** [comment]
The problem with post is the CRSF validation process, so sadly this won't work. Whats wrong with GET, suggestions?

**Comment by nadar** [comment]
So if we want to use post, we have to set csrf token. But again, what is the benefit from post over get, the only thing i could image so we don't have to build those urls. But post might have other problems with other forms.

**Comment by JohnnyMcWeed** [comment]
The url is enough to make it correct :)
What else needs to be adjusted?
Seems to be working with the contact form like this...

**Comment by nadar** [comment]
The post request might conflict with other forms on the side, as this dialog will be on every page its hard to test all the scenarios. What if pjax is used, does that work? And again, what is the benefit from post over get?

**Comment by JohnnyMcWeed** [comment]
I can test Pjax at a later moment.

What's the problem about it?

- It's not a clean url
- Some SEO tools have problems (one part is more crawling than needed; others have problem with duplicate content tools; etc.)
- Not quite sure about duplicate content/the canonical built in... (I did not check this, hope this works out of the box. I'm currently going with the adjusted version, will test this later)
- It can confuse crawlers and split page ranking signals
- If someone goes to a page and shares that link, it bypasses the way the privacy mechanism should work

**Comment by nadar** [comment]
Good elaborated, seems reasonable. Lets see if everything works with pjax. Maybe we need further tests.

**Comment by nadar** [comment]
@JohnnyMcWeed tests seems to fail
@boehsermoe review?

**Review by nadar — CHANGES_REQUESTED** [review]
Tests are failing

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.

**Comment by nadar** [comment]
I am going to close this PR because:

- The PR has no activity for a long time.
- The PR does not have Unit Tests.
- The PR is not valid.
- The PR author does not respond to questions are comments.

> If the author (you) or someone is picking up the PR again, feel free to reopen. We **don't want to wast the time you have spent on the PR**. Also if you need help please let us know. Its not our aim to close PR's but we want to keep the repository activity as clean as possible.

If you think this is still important or there are more/new informations. **Please reopen the PR and let us know**.

**Pull request closed without merging**
