### PR TITLE
Corrected attribute

### PR DESCRIPTION
**Pull request by JohnnyMcWeed**
### What are you changing/introducing
Corrected attribute name

### What is the reason for changing/introducing
Last commit had an error with the attribute name

(How do you want to treat whitespaces? Like this? Or just don't care about it?)

### CODE REVIEW

**Comment by nadar** [comment]
> (How do you want to treat whitespaces? Like this? Or just don't care about it?)

What do you mean? Which whitespace?

**Comment by JohnnyMcWeed** [comment]
I'm talking about this:

`<div class="luya-privacy-widget-container<?= (!empty($containerCssClass)) ? ' '.$containerCssClass : '' ?>">`

**Comment by nadar** [comment]
This looks good to me - nothing wrong, no white space as far as i can see.

**Comment by JohnnyMcWeed** [comment]
Hey, sure. I was just wondering whether there would be something "easier" without that whitespace in the empty clause.

So then it should be ok now, tests pass.

**Comment by nadar** [comment]
Thanks @JohnnyMcWeed i will enable travis as soon as i have time

**Pull request merged**
